defaults:
  - _self_
  - hydra: defaults
  - model: gaussian
  - dataset: re10k
  - loss: [reconstruction]

config:
  exp_name: "debug"
  file: "config.yaml"

data_loader:
  batch_size: 4
  num_workers: 16

train:
  logging: true
  mixed_precision: 16-mixed 
  num_gpus: [1,2,3,4]  # 多GPU设备编号
  load_weights_folder: null
  ema:
    use: true
    update_every: 10
    update_after_step: 100
    beta: 0.9999

optimiser:
  learning_rate: 1e-4
  num_epochs: 1
  scheduler_lambda_step_size: 10000

run:
  resume_ckpt: null
  dirpath: null
  debug: false
  random_seed: 42
  git_hash: null
  log_frequency: 250
  save_frequency: 5000
  val_frequency: 5000
  num_keep_ckpts: 5
  weights_path: null
triplane:
  plane_size: 32
  num_channels: 64

unidepth:
  version: v2
  backbone: vitl14

model:
  attn_heads: 8
  attn_dim_head: 64
  attn_layers: 2
  use_checkpoint: False
  context_dim: [512, 512]  
  encoder:
    out_channels: 512  
  disable_self_attn: false  
  num_frames: 1  